### ISSUE TITLE
Creating new project results in damaged project that cannot run

### ISSUE THREAD

**Issue by developer82** [appcelerator/atom-appcelerator-titanium#115] opened 2018-07-05 21:06 UTC
When creating a new Titanium project using the plugin the project is created, but when trying to run it, an exception is thrown and the project is not run:
```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
Build failed. Process exited with code 3.
```

When creating a project in Appcelerator Studio (on the same machine) and running it from the Arom plugin it runs without any problem.

**Comment by hansemannn** [comment] 2018-07-16 07:30
I cannot reproduce this, sorry. It seems to be an issue with the underlaying V8 engine of Atom (Electron), so an update might help there.

**Comment by ewanharris** [comment] 2018-11-13 14:35
I'm unable to reproduce this issue and create and then run a Titanium app just fine from Atom 1.32.2 with version 1.4.2 of this package.

@developer82, if this issue happens again for you please file another issue. I'm going to close this one out.

**Closed by ewanharris** 2018-11-13 14:35 UTC
Labels: bug, cannot reproduce
