### ISSUE TITLE
Uncaught SyntaxError: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by mlcunha** [appcelerator/atom-appcelerator-titanium#68] opened 2017-12-11 19:46 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.0.2

### Stack Trace

Uncaught SyntaxError: Unexpected token A in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at exit (/packages/appcelerator-titanium/lib/appc.js:25:23)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -2:22.8.0 core:confirm (input.hidden-input)
  8x -0:47.3.0 core:backspace (input.hidden-input)
     -0:33.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
appcelerator-titanium 1.0.2 
```

**Comment by hansemannn** [comment] 2017-12-11 22:59
Duplicate of https://github.com/appcelerator/atom-appcelerator-titanium/issues/67, please use the appc-cli.

**Closed by hansemannn** 2017-12-11 22:59 UTC
