### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by testampat** [appcelerator/atom-appcelerator-titanium#341] opened 2020-10-21 20:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.13.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/v412636/.atom/packages/appcelerator-titanium/node_modules/etch/lib/dom.js:16

RangeError: Maximum call stack size exceeded
    at Object.dom (/packages/appcelerator-titanium/node_modules/etch/lib/dom.js:16:20)
    at ConsoleLog.render (/packages/appcelerator-titanium/lib/ui/console.jsx:41:4)
    at updateSync (/packages/appcelerator-titanium/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/appcelerator-titanium/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326516)
```

### Commands

```
     -0:03.6.0 application:quit (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.13.0 
atom-beautify 0.33.4 
Hydrogen 2.14.6 
teletype 0.13.4 
```

**Comment by ewanharris** [comment] 2020-10-23 11:12
Looks to be a dupe of #341, so closing

**Closed by ewanharris** 2020-10-23 11:12 UTC
